languageCode = "en-us"
title = "My tech blog"
theme = "one-post-a-year"
baseURL = 'https://jarv.github.io/one-post-a-year'
description = ""

pygmentsCodeFences = true

[markup.goldmark.renderer]
  unsafe = "true"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    # https://xyproto.github.io/splash/docs/longer/all.html
    style = 'github'
    tabWidth = 4
